# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample Rcpp function
#'
#' @return TRUE
#' @export
rcpp_hello_world <- function() {
    .Call('_testRcppTravis_rcpp_hello_world', PACKAGE = 'testRcppTravis')
}

#' Sample Rcpp function, exported to R but hidden (not in the NAMESPACE)
#'
#' @return TRUE
rcpp_hello_world_hidden <- function() {
    .Call('_testRcppTravis_rcpp_hello_world_hidden', PACKAGE = 'testRcppTravis')
}

#' Sample Rcpp function, exported to R but internal
#'
#' @return TRUE
#' @keywords internal
rcpp_hello_world_internal <- function() {
    .Call('_testRcppTravis_rcpp_hello_world_internal', PACKAGE = 'testRcppTravis')
}

#' Sample Rcpp function, calling an internal function in C++
#' 
#' @export
rcpp_hello_world_source_call <- function() {
    .Call('_testRcppTravis_rcpp_hello_world_source_call', PACKAGE = 'testRcppTravis')
}

